#!/usr/bin/env node
// Generates the hero: papercut layering in greys, grounds alternating layer by layer.
//
// Call:  node _scripts/build-hero.mjs   (after npm run tokens and npm run imagery)
//
// WHAT A HERO IS HERE. One silhouette repeated at increasing insets with a soft shadow
// between layers. No colour: the references that prompted the construction were
// saturated, and only the construction was adoptable. Every parameter is decided
// elsewhere in this repository:
//
//   LAYER COUNT = 3, the series count in imagery/series.json.
//   FILLS ALTERNATE GROUNDS (series-patterns.mjs, alternatingLayers): layer 1 solid ink,
//   layer 2 a grey 45° hatch on the paper tone, layer 3 a grey cross-hatch on the ink
//   tone. Grey on white and grey on black are both inside the no-colour rule, and
//   alternating them makes every cut edge light against dark in both bands — depth is
//   carried by ground, by geometry and by the shadow at once.
//   INSET = 48px per side per layer, --space-7.
//   SHADOW = 12px, one quarter of the inset, dy 4px (--space-1): a blur wider than half
//   the ring bridges two layers and the stack reads as one blob. Checked below.
//   SILHOUETTE = the mark, scaled about its centre — placed point by point in canvas
//   space, so the patterns keep their 4px and 5px periods.
//
// THE FIELD is a gradient between --paper and --paper-dim, both pure greys, sampled
// into stops because SVG interpolates in sRGB and cannot declare OKLCH.
//
// THE SHADOW IS THE ONLY ALPHA IN THE SYSTEM, confined to the imagery layer.

import { writeFileSync, mkdirSync, readFileSync } from "node:fs";
import { converter, formatHex, parse } from "culori";
import { alternatingLayers, markPathAt, assertMonochrome } from "./series-patterns.mjs";

const ok = converter("oklch");
const grey = (l) => formatHex({ mode: "oklch", l, c: 0, h: 0 });

const VB = 64;                          // the mark's box, from assets/mark.mjs
const MARK = [[6, 6], [23.68, 14.32], [32, 32], [40.32, 49.68], [58, 58], [58, 6]];
const W = 1200, H = 630;                // the Open Graph frame, reused
const INSET = 48, BLUR = 12, DY = 4;    // --space-7, --space-3, --space-1
const OPACITY = 0.25;
const ART = H - 2 * INSET;
const SIDES = [ART, ART - 2 * INSET, ART - 4 * INSET];

const tokens = JSON.parse(readFileSync("tokens/tokens.json", "utf8"));
const series = JSON.parse(readFileSync("imagery/series.json", "utf8"));
const GROUND = Object.fromEntries(["light", "dark"].map((b) => [b, {
  paper: tokens.bands[b].grounds.paper, dim: tokens.bands[b].grounds.dim, ink: tokens.bands[b].roles.ink,
}]));
const LAYERS = Object.fromEntries(["light", "dark"].map((b) => [b, alternatingLayers(series.bands[b].series, GROUND[b].paper)]));

/** The lightness path between two grey grounds, sampled fine enough not to band. */
function stopsFor(aHex, bHex) {
  const a = ok(parse(aHex)).l, b = ok(parse(bHex)).l;
  const n = Math.min(24, Math.max(2, Math.ceil(Math.abs(a - b) * 255 / 2) + 1));
  return Array.from({ length: n }, (_, i) => {
    const t = i / (n - 1);
    return { off: +(t * 100).toFixed(2), hex: grey(a + (b - a) * t) };
  });
}

function hero(band) {
  const g = GROUND[band], layers = LAYERS[band];
  const st = stopsFor(g.paper, g.dim);
  const paths = SIDES.map((side, i) => {
    const k = side / VB, x = (W - side) / 2, y = (H - side) / 2;
    return `  <path d="${markPathAt(MARK, VB, x, y, k)}" fill="${layers[i].fill}" fill-rule="evenodd" filter="url(#lift)"></path>`;
  }).join("\n");
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="Hero, ${band} band">
<title>Hero, ${band} band</title>
<desc>Papercut layering in greys. GENERATED by _scripts/build-hero.mjs; every parameter derived, recorded in imagery/hero.json. Three layers because three is the series count; the grounds alternate — layer 1 solid ink, layer 2 a grey hatch on paper, layer 3 a grey cross-hatch on ink — so every cut edge is light against dark; inset ${INSET}px per side per layer (space step 7); shadow radius ${BLUR}px, one quarter of the inset; field sampled at ${st.length} stops.</desc>
<defs>
  <linearGradient id="field" x1="0" y1="0" x2="0" y2="1">
${st.map((s) => `    <stop offset="${s.off}%" stop-color="${s.hex}"></stop>`).join("\n")}
  </linearGradient>
  ${layers.map((l) => l.def).join("")}
  <filter id="lift" x="-10%" y="-10%" width="120%" height="120%">
    <feDropShadow dx="0" dy="${DY}" stdDeviation="${BLUR}" flood-color="${g.ink}" flood-opacity="${OPACITY}"></feDropShadow>
  </filter>
</defs>
<rect width="${W}" height="${H}" fill="url(#field)"></rect>
${paths}
</svg>
`;
}

if (BLUR > INSET / 2) {
  console.error(`FAILED: shadow ${BLUR}px exceeds half the ${INSET}px inset — the layers would bridge.`);
  process.exit(1);
}

const out = {
  "imagery/hero-light.svg": hero("light"),
  "imagery/hero-dark.svg": hero("dark"),
  "imagery/hero.json": JSON.stringify({
    $comment: "GENERATED by _scripts/build-hero.mjs — do not edit by hand.",
    canvas: { w: W, h: H, ratio: "40:21, the Open Graph frame" },
    layers: SIDES.length,
    layerSource: "the series count in imagery/series.json",
    sides: SIDES, insetPerLayer: INSET, insetToken: "--space-7",
    shadow: { stdDeviation: BLUR, token: "--space-3", dy: DY, dyToken: "--space-1", floodOpacity: OPACITY,
              rule: "radius is one quarter of the inset, so a shadow never bridges two layers" },
    fills: Object.fromEntries(["light", "dark"].map((b) => [b, LAYERS[b].map(({ pattern, ground, line }) => ({ pattern, ground, line }))])),
    fillRule: "grounds alternate ink, paper, ink; lines are the series greys — grey on white and grey on black are not colours",
    field: Object.fromEntries(["light", "dark"].map((b) => [b, {
      from: GROUND[b].paper, to: GROUND[b].dim, stops: stopsFor(GROUND[b].paper, GROUND[b].dim).length,
      interpolation: "lightness, sampled — SVG interpolates in sRGB, so the path is emitted as stops",
    }])),
    silhouette: "the mark itself (bend), scaled about its centre and placed in canvas space so the patterns keep their period",
    colour: "none — black, grey and white; depth carried by alternating grounds, by pattern and by the shadow",
    alpha: "the drop shadow is the only alpha in the system, and it lives inside the imagery layer, never in chrome",
  }, null, 2) + "\n",
};
for (const [f, text] of Object.entries(out)) assertMonochrome(f, text);
mkdirSync("imagery", { recursive: true });
for (const [f, text] of Object.entries(out)) writeFileSync(f, text);
console.log(`Hero      ${SIDES.length} layers (solid ink / grey hatch on paper / grey cross-hatch on ink)  inset ${INSET}  shadow ${BLUR} (dy ${DY})`);
console.log("Written: imagery/hero-light.svg, imagery/hero-dark.svg, imagery/hero.json");
