#!/usr/bin/env node
// Generates the rest of the imagery layer: spots, the banner, the ornament — and
// records the three classes this system refuses to ship, with the reason.
//
// Call:  node _scripts/build-figures.mjs   (after npm run tokens and npm run imagery)
//
// All of it is the papercut construction from build-hero.mjs at other sizes, which
// is the point: one construction, many classes, and the differences between them
// computed rather than drawn. Like the hero it carries no colour: every layer is a grey
// series, and series 2 and 3 are their patterns (_scripts/series-patterns.mjs).
//
// THE LAYER-DROP RULE. A ring narrower than 8px stops reading as cut paper — 8px is
// --space-2, the smallest step in the scale that is not simply a pair of hairlines.
// The hero's ring is 7.62 % of its side (48 of 630), so holding three layers below
// about 105px would mean rings nobody can see. Below that the figure DROPS A LAYER
// and the remaining rings widen to keep the proportion. Measured: 630px → 3 layers
// at 48px rings, 272px → 3 at 20.7, 96px → 2 at 11.0, 64px → 1 and no ring at all.
//
// THAT RULE IS THE THUMBNAIL RULE. A thumbnail is not a shrunk anything: it is the
// same figure with the layer count its size can carry.
//
// WHAT IS NOT SHIPPED, AND WHY. Three classes are refused rather than faked:
//
//   KEY ART is campaign-level, and there is no campaign.
//
//   SCRIM is alpha. Text never sits on imagery: the hero splits rather than overlays.
//   The one alpha value in the whole system is the papercut drop shadow.
//
//   CARD IMAGE, as a per-item drawing. This system has one mark; a per-item variation
//   of it would be decoration pretending to be identification. The card image here is
//   the SECTION's spot, shared by every item under that heading.

import { writeFileSync, mkdirSync, readFileSync } from "node:fs";
import { converter, formatHex, parse } from "culori";
import { patternDefs, fillFor, markPathAt, assertMonochrome } from "./series-patterns.mjs";

const ok = converter("oklch");
const grey = (l) => formatHex({ mode: "oklch", l, c: 0, h: 0 });

const VB = 64;
const MARK = [[6, 6], [23.68, 14.32], [32, 32], [40.32, 49.68], [58, 58], [58, 6]];
const RING_MIN = 8;              // --space-2
const INSET_RATIO = 48 / 630;    // the hero's ring, as a fraction of its side
const tokens = JSON.parse(readFileSync("tokens/tokens.json", "utf8"));
const series = JSON.parse(readFileSync("imagery/series.json", "utf8"));
const GROUND = Object.fromEntries(["light", "dark"].map((b) => [b, {
  paper: tokens.bands[b].grounds.paper, dim: tokens.bands[b].grounds.dim, ink: tokens.bands[b].roles.ink,
}]));

function layersFor(side) {
  for (const n of [3, 2, 1]) {
    const inset = n === 1 ? 0 : side * INSET_RATIO * (3 / n);
    if (n === 1 || inset >= RING_MIN) return { n, inset: +inset.toFixed(2) };
  }
}

function stack(side, band, x0, y0, rot, seriesFrom) {
  const { n, inset } = layersFor(side);
  const ser = series.bands[band].series;
  let svg = "";
  for (let i = 0; i < n; i++) {
    const s = side - 2 * inset * i, k = s / VB;
    const x = x0 + (side - s) / 2, y = y0 + (side - s) / 2;
    svg += `<path d="${markPathAt(MARK, VB, x, y, k, rot)}" fill="${fillFor(ser, Math.min(2, seriesFrom + i))}" fill-rule="evenodd" filter="url(#lift)"></path>`;
  }
  return { svg, n, inset };
}

const defs = (band, blur, extra = "") => `<defs>${extra}${patternDefs(series.bands[band].series)}<filter id="lift" x="-12%" y="-12%" width="124%" height="124%">`
  + `<feDropShadow dx="0" dy="${+(blur / 3).toFixed(2)}" stdDeviation="${+blur.toFixed(2)}" flood-color="${GROUND[band].ink}" flood-opacity="0.25"></feDropShadow></filter></defs>`;

function stopsFor(aHex, bHex) {
  const a = ok(parse(aHex)).l, b = ok(parse(bHex)).l;
  const n = Math.min(24, Math.max(2, Math.ceil(Math.abs(a - b) * 255 / 2) + 1));
  return Array.from({ length: n }, (_, i) => ({ off: +((i / (n - 1)) * 100).toFixed(2), hex: grey(a + (b - a) * (i / (n - 1))) }));
}

const out = {};

// SPOT — 96px, two layers by the rule. Three of them, because there are three
// sections and three series. Rotation distinguishes them without a second drawing.
for (const band of ["light", "dark"]) {
  for (const [i, rot] of [[0, 0], [1, 90], [2, 180]]) {
    const side = 96, st = stack(side, band, 0, 0, rot, i === 2 ? 0 : i);
    out[`imagery/spot-${i + 1}-${band}.svg`] = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${side} ${side}" width="${side}" height="${side}" role="img" aria-label="Spot ${i + 1}, ${band} band"><title>Spot ${i + 1}, ${band} band</title><desc>GENERATED by _scripts/build-figures.mjs. ${st.n} layers at ${st.inset}px rings, rotation ${rot} degrees, series ${i + 1} outward, greys and patterns only. Parameters in imagery/figures.json.</desc>${defs(band, st.inset / 4)}${st.svg}</svg>\n`;
  }
}

// BANNER — wide, short, carries text set in the viewer's fallback stack: an SVG loaded
// as an image reaches no webfont, so the line is short, single and left-aligned.
for (const band of ["light", "dark"]) {
  const W = 1280, H = 320, side = H - 48;
  const st = stack(side, band, W - side - 48, 24, 0, 0);
  const sf = stopsFor(GROUND[band].paper, GROUND[band].dim);
  const field = `<linearGradient id="field" x1="0" y1="0" x2="1" y2="0">${sf.map((s) => `<stop offset="${s.off}%" stop-color="${s.hex}"></stop>`).join("")}</linearGradient>`;
  out[`imagery/banner-${band}.svg`] = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="Anselm W. Hahn — scientific software and its provenance"><title>Anselm W. Hahn</title><desc>Banner, ${band} band. GENERATED by _scripts/build-figures.mjs. Text is set in the viewer's fallback stack: an SVG loaded as an image cannot reach a webfont.</desc>${defs(band, st.inset / 4, field)}<rect width="${W}" height="${H}" fill="url(#field)"></rect>${st.svg}<text x="64" y="150" font-family="Inter, 'Helvetica Neue', Arial, sans-serif" font-size="62" font-weight="700" letter-spacing="-1.36" fill="${GROUND[band].ink}">Anselm W. Hahn</text><text x="64" y="196" font-family="Inter, 'Helvetica Neue', Arial, sans-serif" font-size="23" font-weight="400" fill="${GROUND[band].ink}" opacity="0.72">Scientific software and its provenance</text></svg>\n`;
}

// ORNAMENT — the mark at 16px on a rule. One layer, by the rule: at 16px a ring would
// be 1.2px, well under the floor, so the figure drops to a single silhouette.
for (const band of ["light", "dark"]) {
  const W = 240, H = 24, m = 16, k = m / VB, tone = series.bands[band].series[1].hex;
  out[`imagery/ornament-${band}.svg`] = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="presentation" aria-hidden="true"><title>Ornament, ${band} band</title><desc>GENERATED by _scripts/build-figures.mjs. One layer: at 16px the ring would be 1.2px, under the 8px floor.</desc><path d="M 0 ${H / 2} H ${(W - m) / 2 - 12} M ${(W + m) / 2 + 12} ${H / 2} H ${W}" stroke="${tone}" stroke-width="1"></path><path d="${markPathAt(MARK, VB, (W - m) / 2, (H - m) / 2, k)}" fill="${tone}" fill-rule="evenodd"></path></svg>\n`;
}

for (const [f, text] of Object.entries(out)) assertMonochrome(f, text);
mkdirSync("imagery", { recursive: true });
for (const [f, text] of Object.entries(out)) writeFileSync(f, text);

console.log("Side   Layers   Ring");
for (const s of [630, 272, 96, 64]) { const l = layersFor(s); console.log(String(s).padEnd(7) + String(l.n).padEnd(9) + l.inset); }
console.log(`\nWritten: ${Object.keys(out).length} files (greys and patterns only)`);
console.log("Refused, on purpose: key art (no campaign), scrim (alpha), per-item card image (one mark)");
