#!/usr/bin/env node
// Fetch the self-hosted fonts. BUILD TIME, never runtime.
//
// That distinction is the whole point. A fetch while building is a dependency; a
// fetch in the reader's browser is a foreign host on someone else's page. The system
// set out to remove foreign runtime hosts, and until now tokens/typography.css still
// pulled from fonts.googleapis.com while the README generator reported "zero foreign
// runtime hosts". One of those two statements had to give.
//
// Both families are SIL OFL 1.1, which permits self-hosting explicitly. The variable
// latin subsets are small: Inter about 47 KB, JetBrains Mono about 30 KB.
//
// WHY THE CDN AND NOT THE UPSTREAM RELEASE: subsetting needs a font-parsing tool, and
// none is installed (pyftsubset, fonttools, woff2_compress are all absent). The upstream
// zips are 33 MB and 5.5 MB of every format and every subset. So the files come from the
// CDN, which serves the same OFL fonts already subset — while the VERSION is tracked
// against the authoritative source (the upstream GitHub releases), not against the CDN's
// opaque path segment. .github/workflows/font-updates.yml does that tracking.
//
// Every downloaded file is recorded in tokens/fonts.json with its sha256. Without a
// checksum a swapped file would pass unnoticed, and the whole type scale rests on
// these metrics.

import { writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";

const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
           "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const FAMILIES = [
  { family: "Inter", file: "inter-latin-var.woff2",
    css: "https://fonts.googleapis.com/css2?family=Inter:wght@400..700&display=swap",
    upstream: "rsms/inter", license: "SIL OFL 1.1" },
  { family: "JetBrains Mono", file: "jetbrains-mono-latin-var.woff2",
    css: "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400..500&display=swap",
    upstream: "JetBrains/JetBrainsMono", license: "SIL OFL 1.1" },
];

/** The latin block is the one whose unicode-range starts at U+0000-00FF. */
function latinUrl(css) {
  const blocks = css.split("@font-face").slice(1);
  for (const b of blocks) {
    if (!/unicode-range:\s*U\+0000-00FF/.test(b)) continue;
    const m = b.match(/src:\s*url\((https:\/\/[^)]+\.woff2)\)/);
    if (m) return m[1];
  }
  return null;
}

async function upstreamVersion(repo) {
  try {
    const r = await fetch(`https://api.github.com/repos/${repo}/releases/latest`,
      { headers: { Accept: "application/vnd.github+json", "User-Agent": UA } });
    if (!r.ok) return null;
    const j = await r.json();
    return { tag: j.tag_name, published: (j.published_at || "").slice(0, 10) };
  } catch { return null; }
}

mkdirSync("assets/fonts", { recursive: true });
const record = [];

for (const f of FAMILIES) {
  const cssRes = await fetch(f.css, { headers: { "User-Agent": UA } });
  if (!cssRes.ok) { console.error(`${f.family}: stylesheet ${cssRes.status}`); process.exit(1); }
  const url = latinUrl(await cssRes.text());
  if (!url) { console.error(`${f.family}: no latin block found in the stylesheet`); process.exit(1); }

  const fontRes = await fetch(url, { headers: { "User-Agent": UA } });
  if (!fontRes.ok) { console.error(`${f.family}: font ${fontRes.status}`); process.exit(1); }
  const bytes = Buffer.from(await fontRes.arrayBuffer());

  // A woff2 file starts with the signature "wOF2". Checking it costs nothing and
  // catches the case where a CDN hands back an error page with status 200.
  if (bytes.subarray(0, 4).toString("latin1") !== "wOF2") {
    console.error(`${f.family}: downloaded file is not woff2 — refusing to write it`);
    process.exit(1);
  }

  writeFileSync(`assets/fonts/${f.file}`, bytes);
  const up = await upstreamVersion(f.upstream);
  record.push({
    family: f.family, file: `assets/fonts/${f.file}`,
    bytes: bytes.length, sha256: createHash("sha256").update(bytes).digest("hex"),
    license: f.license, sourceUrl: url, upstream: f.upstream,
    upstreamVersion: up?.tag ?? null, upstreamPublished: up?.published ?? null,
    fetchedAt: new Date().toISOString().slice(0, 10),
  });
  console.log(`  ${f.family.padEnd(16)} ${String(Math.round(bytes.length / 1024)).padStart(4)} KB` +
              `  upstream ${up?.tag ?? "unknown"}`);
}

writeFileSync("tokens/fonts.json", JSON.stringify({
  $comment: "GENERATED by _scripts/fetch-fonts.mjs. The sha256 is the point: without it a " +
            "swapped font file would pass unnoticed, and the entire type scale rests on " +
            "these metrics. .github/workflows/font-updates.yml checks both the upstream " +
            "version and these checksums.",
  whyBuildTime: "Fetched while building, never at runtime. A build-time fetch is a " +
                "dependency; a runtime fetch is a foreign host on the reader's page.",
  fonts: record,
}, null, 2) + "\n");

const total = record.reduce((a, r) => a + r.bytes, 0);
console.log(`\ntokens/fonts.json written — ${record.length} families, ${Math.round(total / 1024)} KB total.`);
console.log("A font update invalidates the size-adjust values in tokens/font-chain.css.");
console.log("Re-measure them before trusting the fallbacks again.");
